name: Push builds

on:
  push:
    branches:
      - main

jobs:
  build-web:
    permissions:
      contents: write

    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-4.2.1.yml@main
    with:
      platform: Web
      name: summon-sandbox
      output_name: index.html

  build-windows:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-4.2.1.yml@main
    with:
      platform: Windows
      name: summon-sandbox
      output_name: SummonSandbox.exe

  build-mac:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-4.2.1.yml@main
    with:
      platform: macOS
      name: summon-sandbox
      output_name: SummonSandbox.macos.zip

  build-linux:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-4.2.1.yml@main
    with:
      platform: Linux
      name: summon-sandbox
      output_name: SummonSandbox.linux.x86_64